"""
Clean Parameters Engine for TASL AERO-SENSE
Defines the authoritative 62 monitored parameters for Bavius 4mtr N01-02
with OEM manual limits, physical ranges, directions, and precise warning/alarm thresholds.
"""
import json
import os

def get_bavius_parameters():
    groups = [
        {
            "groupId": "spindle-dynamics",
            "groupName": "Main Spindle Dynamics & Thermal Monitoring (SP1)",
            "description": "Fischer MFW-1920/30/1 Hybrid Ceramic Spindle parameters, PT100 sensors, torque and motor power per Fischer Spindle Manual Ch. 7.2",
            "parameters": [
                {
                    "tag": "BAVIUS_4MTR_SPINDLE_actSpeed",
                    "name": "Spindle Actual Speed",
                    "value": 23890.0,
                    "unit": "RPM",
                    "direction": "high",
                    "min": 0,
                    "max": 30000,
                    "warnLimit": 25000.0,
                    "alarmLimit": 28500.0,
                    "normal": "0 - 25,000 RPM",
                    "alarm": "> 28,500 RPM",
                    "backendZone": "green",
                    "sparkline": [0, 8000, 16000, 22000, 23800, 23900, 23850, 23920, 23870, 23890],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_4M_SPINDLE_BEARING_TEMP_1",
                    "name": "Spindle Front Bearing Temperature (DE)",
                    "value": 33.4,
                    "unit": "°C",
                    "direction": "high",
                    "min": 15,
                    "max": 65,
                    "warnLimit": 45.0,
                    "alarmLimit": 50.0,
                    "normal": "20 - 45 °C",
                    "alarm": "≥ 50 °C",
                    "backendZone": "green",
                    "sparkline": [26.0, 27.2, 28.5, 29.8, 31.0, 32.1, 32.8, 33.0, 33.2, 33.4],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_4M_SPINDLE_BEARING_TEMP_2",
                    "name": "Spindle Rear Bearing Temperature (NDE)",
                    "value": 42.6,
                    "unit": "°C",
                    "direction": "high",
                    "min": 15,
                    "max": 60,
                    "warnLimit": 40.0,
                    "alarmLimit": 48.0,
                    "normal": "20 - 40 °C",
                    "alarm": "≥ 48 °C",
                    "backendZone": "yellow",
                    "sparkline": [30.1, 32.4, 34.8, 37.0, 39.2, 40.8, 41.5, 42.0, 42.4, 42.6],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Spindle Rear Bearing Temp reached 42.6 °C, exceeding 40.0 °C warning threshold.",
                        "probableReason": "Air-oil micro-lubrication dosing interval restricted or high ambient spindle nose friction.",
                        "manualSolution": "1. Inspect oil-air lubrication unit reservoir level and dosing pressure (2.8 bar nominal).\n2. Verify pulse cycle frequency (1 shot every 8 mins) per Fischer Manual Ch. 4.3.\n3. Check recooler cooling jacket supply lines for thermal balance.",
                        "historicalCorrelation": "Led to bearing thermal alert 4 times in the past 6 months (Last: 12-Sep-2026).",
                        "sparesRequired": "Fischer Ceramic Ball Bearing Set (P/N: HC-7012-C-P4S), Turcon Variseal Shaft Oil Seal (P/N: TVS-35x50x7), Air-Oil Micro-Lubrication Injector Nozzle (P/N: VOE-02-NOZ)"
                    }
                },
                {
                    "tag": "BAVIUS_4MTR_SP1_MOTOR_TEMP",
                    "name": "Spindle Motor Stator Temperature (PTC)",
                    "value": 61.4,
                    "unit": "°C",
                    "direction": "high",
                    "min": 15,
                    "max": 80,
                    "warnLimit": 50.0,
                    "alarmLimit": 60.0,
                    "normal": "20 - 50 °C",
                    "alarm": "≥ 60 °C (Trip)",
                    "backendZone": "red",
                    "sparkline": [38.0, 42.0, 47.0, 52.0, 55.0, 57.5, 59.0, 60.2, 61.0, 61.4],
                    "analysis": {
                        "severity": "Critical",
                        "riskyTrend": "Critical thermal overload: Stator Temp climbed to 61.4 °C, breaching the 60.0 °C alarm threshold.",
                        "probableReason": "Spindle thermal saturation due to recooler heat dissipation deficit. KRA150 chiller filter mat clogged.",
                        "manualSolution": "1. Execute controlled spindle stop.\n2. Clean KRA150 chiller air filter mat FAC and remove debris from condenser fins.\n3. Measure PTC resistance (< 3000 Ω across pins 3-4 per Fischer Manual Ch. 7.2).\n4. Allow 30 min cooling dwell and restart under graduated warm-up cycle.",
                        "historicalCorrelation": "Corresponds to Active Breakdown Ticket SAP-PM-2026-94812 (Occurred 3 times in last 6 months).",
                        "sparesRequired": "Rittal Chiller G4 Air Filter Mat (P/N: SK 3182.100), Fischer PTC M130 Thermistor Sensor (P/N: DIN 44082 M130), Coolant Circulation Pump Mechanical Seal (P/N: KRA-150-MS)"
                    }
                },
                {
                    "tag": "BAVIUS_4MTR_aaCurr_SP1",
                    "name": "Spindle Stator Active Current",
                    "value": 18.8,
                    "unit": "A",
                    "direction": "high",
                    "min": 0,
                    "max": 35,
                    "warnLimit": 16.0,
                    "alarmLimit": 24.0,
                    "normal": "0 - 16 A",
                    "alarm": "≥ 24 A (Overload)",
                    "backendZone": "yellow",
                    "sparkline": [4.2, 6.8, 10.5, 13.8, 15.6, 17.2, 18.0, 18.5, 18.6, 18.8],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Stator active current drawing 18.8 A, operating above 16.0 A normal cut load boundary.",
                        "probableReason": "Increased milling tool engagement friction, workpiece chip re-cutting, or high cutting depth.",
                        "manualSolution": "1. Inspect CNC programmed cutting feedrate and spindle load display.\n2. Inspect cutting tool insert flutes for micro-chipping or flank wear.\n3. Verify toolholder HSK-A63 taper seating per Fischer Manual Ch. 5.1.",
                        "historicalCorrelation": "Led to spindle load warning 7 times in last 6 months (Last: 18-Sep-2026).",
                        "sparesRequired": "HSK-A63 Tool Holder Collet (P/N: OTT-JAKOB 95.600.034.9.2), Fischer Spindle Grounding Brush Kit (P/N: GB-1920-KIT), Solid Carbide End Mill Inserts (P/N: APKT 1003 PDR)"
                    }
                },
                {
                    "tag": "BAVIUS_4MTR_vaTorque_SP1",
                    "name": "Spindle Motor Torque",
                    "value": 7.8,
                    "unit": "Nm",
                    "direction": "high",
                    "min": 0,
                    "max": 25,
                    "warnLimit": 12.0,
                    "alarmLimit": 18.0,
                    "normal": "0 - 12.0 Nm",
                    "alarm": "≥ 18.0 Nm",
                    "backendZone": "green",
                    "sparkline": [1.5, 3.2, 5.1, 6.4, 7.1, 7.5, 7.6, 7.7, 7.8, 7.8],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_4MTR_SP1_POWER",
                    "name": "Spindle Drive Active Power",
                    "value": 18.2,
                    "unit": "kW",
                    "direction": "high",
                    "min": 0,
                    "max": 45,
                    "warnLimit": 30.0,
                    "alarmLimit": 38.0,
                    "normal": "0 - 30.0 kW",
                    "alarm": "≥ 38.0 kW",
                    "backendZone": "green",
                    "sparkline": [2.0, 5.8, 11.2, 14.8, 16.5, 17.6, 18.0, 18.1, 18.2, 18.2],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_4MTR_VIB_SP1_FRONT",
                    "name": "Spindle Nose Vibration FFT RMS",
                    "value": 4.85,
                    "unit": "mm/s",
                    "direction": "high",
                    "min": 0,
                    "max": 10,
                    "warnLimit": 2.5,
                    "alarmLimit": 4.5,
                    "normal": "0 - 2.5 mm/s",
                    "alarm": "≥ 4.5 mm/s (Alarm 700731)",
                    "backendZone": "red",
                    "sparkline": [1.2, 1.6, 2.1, 2.8, 3.4, 4.0, 4.3, 4.6, 4.75, 4.85],
                    "analysis": {
                        "severity": "Critical",
                        "riskyTrend": "Spindle FFT vibration rose to 4.85 mm/s, breaching ISO 10816 & SiViB alarm limit 4.5 mm/s.",
                        "probableReason": "Toolholder unbalance (exceeding G2.5) or incipient outer race bearing defect frequency (BPFO).",
                        "manualSolution": "1. Stop cutting cycle and retract spindle to tool-change position.\n2. Inspect HSK-A63 toolholder collar and spindle receiver taper for fretting corrosion.\n3. Measure dynamic runout with dial gauge (< 0.003 mm per Fischer Manual Ch. 7.3).\n4. Inspect SiViB Record 31 FFT diagnostic spectrum for defect frequencies.",
                        "historicalCorrelation": "Led to emergency stop 2 times in last 6 months (Last: 05-Sep-2026).",
                        "sparesRequired": "Fischer Hybrid Ceramic Front Duplex Bearing Pair (P/N: HC-7014-C-P4S-DUL), SiViB Accelerometer Sensor Cable M12 (P/N: 31-CAB-05M), Precision Balancing Ring Kit (P/N: BR-63-A)"
                    }
                },
                {
                    "tag": "BAVIUS_4MTR_TOOL_CLAMP_FORCE",
                    "name": "Tool Clamping Pull-in Force (Ott-Jakob)",
                    "value": 14.2,
                    "unit": "kN",
                    "direction": "low",
                    "min": 0,
                    "max": 25,
                    "warnLimit": 18.0,
                    "alarmLimit": 15.0,
                    "normal": "18.0 - 22.0 kN",
                    "alarm": "< 15.0 kN (Stop)",
                    "backendZone": "red",
                    "sparkline": [18.2, 17.8, 17.1, 16.4, 15.8, 15.2, 14.8, 14.5, 14.3, 14.2],
                    "analysis": {
                        "severity": "Critical",
                        "riskyTrend": "Tool pull-in clamping force dropped to 14.2 kN, below the 15.0 kN critical safe threshold.",
                        "probableReason": "Ott-Jakob drawbar Belleville disc spring stack fatigue or collet gripper claw contamination.",
                        "manualSolution": "1. Inhibit spindle start immediately to avoid toolholder ejection risk.\n2. Calibrate clamping force with Ott-Jakob POWER-CHECK wireless gauge.\n3. Inspect drawbar Belleville spring washers for cracks per Tool Manual 146598 Ch. 3.2.\n4. Clean and lubricate HSK gripper segments with Klüber paste.",
                        "historicalCorrelation": "Precedent recorded 5 times across fleet in last 6 months (Last: 22-Aug-2026).",
                        "sparesRequired": "Belleville Disc Spring Stack 18 kN Pack (P/N: Bavius 146598-BSS), HSK-A63 4-Segment Clamping Gripper (P/N: OTT-JAKOB 95.600.034), Hydraulic Unclamp Piston NBR Seal Kit (P/N: NBR-90-V42)"
                    }
                },
                {
                    "tag": "BAVIUS_4MTR_OIL_AIR_LUBE_P",
                    "name": "Spindle Oil-Air Lubrication Dosing Pressure",
                    "value": 2.8,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 6,
                    "warnLimit": 2.5,
                    "alarmLimit": 1.8,
                    "normal": "2.5 - 4.5 bar",
                    "alarm": "< 1.8 bar",
                    "backendZone": "green",
                    "sparkline": [2.9, 2.8, 2.9, 2.8, 2.8, 2.9, 2.8, 2.8, 2.8, 2.8],
                    "analysis": None
                }
            ]
        },
        {
            "groupId": "chiller-cooling",
            "groupName": "Cooling & Spindle Chiller Recooler System",
            "description": "Rittal KRA150 closed-loop recooler circuit monitoring spindle stator jacket and bearing heat exchanger per KRA150 Chiller Manual",
            "parameters": [
                {
                    "tag": "BAVIUS_CHILLER_SUPPLY_TEMP",
                    "name": "Chiller Recooler Supply Temperature",
                    "value": 25.6,
                    "unit": "°C",
                    "direction": "high",
                    "min": 10,
                    "max": 35,
                    "warnLimit": 24.0,
                    "alarmLimit": 28.0,
                    "normal": "18.0 - 24.0 °C",
                    "alarm": "≥ 28.0 °C",
                    "backendZone": "yellow",
                    "sparkline": [20.8, 21.6, 22.5, 23.4, 24.1, 24.8, 25.2, 25.4, 25.5, 25.6],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Chiller supply coolant temp rose to 25.6 °C, exceeding 24.0 °C setpoint band.",
                        "probableReason": "Air-cooled condenser fin clogging reducing heat transfer efficiency to shop environment.",
                        "manualSolution": "1. Remove KRA150 front grille and vacuum clean condenser coil fins.\n2. Wash G4 filter mat FAC with mild detergent and dry thoroughly.\n3. Verify chiller fan rotation and ambient inlet temperature per Rittal Manual Ch. 4.3.",
                        "historicalCorrelation": "Associated with Spindle Over-Temperature breakdown mode (17 incidents in last 6 months).",
                        "sparesRequired": "Rittal Filter Mat G4 (P/N: SK 3182.100), Danfoss Refrigerant Expansion Valve R134a (P/N: T2/TE2-068Z3206), Chiller Digital Thermostat Probe Pt100 (P/N: PT100-3M-SS)"
                    }
                },
                {
                    "tag": "BAVIUS_CHILLER_RETURN_TEMP",
                    "name": "Chiller Recooler Return Temperature",
                    "value": 28.4,
                    "unit": "°C",
                    "direction": "high",
                    "min": 10,
                    "max": 40,
                    "warnLimit": 30.0,
                    "alarmLimit": 34.0,
                    "normal": "20.0 - 30.0 °C",
                    "alarm": "≥ 34.0 °C",
                    "backendZone": "green",
                    "sparkline": [24.0, 24.8, 25.6, 26.5, 27.2, 27.8, 28.1, 28.3, 28.4, 28.4],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CHILLER_FLOW_RATE",
                    "name": "Spindle Recooler Flow Rate",
                    "value": 9.8,
                    "unit": "L/min",
                    "direction": "low",
                    "min": 0,
                    "max": 20,
                    "warnLimit": 8.5,
                    "alarmLimit": 6.0,
                    "normal": "8.5 - 15.0 L/min",
                    "alarm": "< 6.0 L/min (Alarm 700501)",
                    "backendZone": "green",
                    "sparkline": [10.4, 10.2, 10.0, 9.9, 9.8, 9.9, 9.8, 9.8, 9.8, 9.8],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CHILLER_REFRIG_HP",
                    "name": "Chiller Refrigerant High Pressure (PA Switch)",
                    "value": 18.2,
                    "unit": "bar",
                    "direction": "high",
                    "min": 0,
                    "max": 30,
                    "warnLimit": 21.0,
                    "alarmLimit": 24.0,
                    "normal": "12.0 - 20.0 bar",
                    "alarm": "≥ 24.0 bar (Trip)",
                    "backendZone": "green",
                    "sparkline": [14.5, 15.2, 16.0, 16.8, 17.4, 17.8, 18.0, 18.1, 18.2, 18.2],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CHILLER_LEVEL_PERCENT",
                    "name": "Chiller Coolant Tank Level",
                    "value": 84.0,
                    "unit": "%",
                    "direction": "low",
                    "min": 0,
                    "max": 100,
                    "warnLimit": 60.0,
                    "alarmLimit": 40.0,
                    "normal": "60 - 100 %",
                    "alarm": "< 40 %",
                    "backendZone": "green",
                    "sparkline": [85, 85, 84, 84, 84, 84, 84, 84, 84, 84],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CHILLER_PUMP_P",
                    "name": "Chiller Pump Outlet Pressure",
                    "value": 3.4,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 6,
                    "warnLimit": 2.8,
                    "alarmLimit": 2.0,
                    "normal": "2.8 - 4.5 bar",
                    "alarm": "< 2.0 bar",
                    "backendZone": "green",
                    "sparkline": [3.5, 3.5, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CHILLER_DELTA_T",
                    "name": "Spindle Jacket Thermal Delta T",
                    "value": 2.8,
                    "unit": "°C",
                    "direction": "high",
                    "min": 0,
                    "max": 10,
                    "warnLimit": 5.0,
                    "alarmLimit": 7.0,
                    "normal": "1.0 - 5.0 °C",
                    "alarm": "≥ 7.0 °C",
                    "backendZone": "green",
                    "sparkline": [1.8, 2.0, 2.3, 2.5, 2.7, 2.8, 2.8, 2.8, 2.8, 2.8],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CHILLER_AMBIENT_TEMP",
                    "name": "Recooler Ambient Air Intake Temp",
                    "value": 27.2,
                    "unit": "°C",
                    "direction": "high",
                    "min": 10,
                    "max": 45,
                    "warnLimit": 35.0,
                    "alarmLimit": 40.0,
                    "normal": "18.0 - 35.0 °C",
                    "alarm": "≥ 40.0 °C",
                    "backendZone": "green",
                    "sparkline": [25.0, 25.4, 25.8, 26.2, 26.6, 26.9, 27.0, 27.1, 27.2, 27.2],
                    "analysis": None
                }
            ]
        },
        {
            "groupId": "pneumatics-air",
            "groupName": "Pneumatics & Central Compressed Air Network",
            "description": "Central plant air supply, SMC filter regulator lubricator (FRL) unit, sealing air purges per HBZ CC Operating Instructions Section 2.3",
            "parameters": [
                {
                    "tag": "BAVIUS_PNEUMATIC_SUPPLY_P1",
                    "name": "Compressed Air Supply Pressure",
                    "value": 5.7,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 10,
                    "warnLimit": 6.0,
                    "alarmLimit": 5.2,
                    "normal": "6.0 - 8.0 bar",
                    "alarm": "< 5.2 bar (Alarm 700121)",
                    "backendZone": "yellow",
                    "sparkline": [6.6, 6.4, 6.2, 6.0, 5.9, 5.8, 5.7, 5.8, 5.7, 5.7],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Inlet air pressure declined to 5.7 bar, below nominal 6.0 bar line pressure.",
                        "probableReason": "Central compressor loading cycle drop or minor pressure drop across drag-chain polyurethane lines.",
                        "manualSolution": "1. Inspect central shop air header pressure gauge.\n2. Check water separator auto-drain valve on SMC FRL service unit.\n3. Inspect flexible pneumatic hoses in Z-axis energy chain per HBZ CC Manual Section 2.3.",
                        "historicalCorrelation": "Led to air supply pressure alarm 12 times in last 6 months (Top 3 breakdown cause).",
                        "sparesRequired": "FESTO MS6-LFM 0.01 µm Microfilter Cartridge (P/N: 532789), FESTO VPPM Proportional Pressure Regulator (P/N: VPPM-6L-L-1), Main FRL Drain Valve Auto-Expeller (P/N: DNV-04-AUTO)"
                    }
                },
                {
                    "tag": "BAVIUS_PNEUMATIC_SPINDLE_SEAL_P",
                    "name": "Spindle Sealing Air Purge Pressure",
                    "value": 1.8,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 4,
                    "warnLimit": 1.4,
                    "alarmLimit": 1.0,
                    "normal": "1.5 - 2.5 bar",
                    "alarm": "< 1.0 bar (Alarm 700216)",
                    "backendZone": "green",
                    "sparkline": [1.9, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_PNEUMATIC_SCALE_PURGE_P",
                    "name": "Linear Scale Sealing Air Pressure",
                    "value": 1.5,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 3,
                    "warnLimit": 1.1,
                    "alarmLimit": 0.8,
                    "normal": "1.2 - 2.0 bar",
                    "alarm": "< 0.8 bar",
                    "backendZone": "green",
                    "sparkline": [1.6, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_PNEUMATIC_DEW_POINT",
                    "name": "Pneumatic Filter Regulator Dew Point",
                    "value": 3.2,
                    "unit": "°C",
                    "direction": "high",
                    "min": -20,
                    "max": 20,
                    "warnLimit": 7.0,
                    "alarmLimit": 12.0,
                    "normal": "-10 - 7 °C",
                    "alarm": "≥ 12 °C",
                    "backendZone": "green",
                    "sparkline": [2.8, 2.9, 3.0, 3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_PNEUMATIC_TAPER_BLOW_FLOW",
                    "name": "Tool Taper Air Blow Purge Flow",
                    "value": 145,
                    "unit": "L/min",
                    "direction": "low",
                    "min": 0,
                    "max": 250,
                    "warnLimit": 110,
                    "alarmLimit": 80,
                    "normal": "110 - 200 L/min",
                    "alarm": "< 80 L/min",
                    "backendZone": "green",
                    "sparkline": [150, 148, 146, 145, 145, 145, 145, 145, 145, 145],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_PNEUMATIC_DOOR_ACT_P",
                    "name": "Shutter Door Actuator Air Pressure",
                    "value": 5.6,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 10,
                    "warnLimit": 4.8,
                    "alarmLimit": 4.0,
                    "normal": "5.0 - 7.0 bar",
                    "alarm": "< 4.0 bar",
                    "backendZone": "green",
                    "sparkline": [5.8, 5.7, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_PNEUMATIC_ATC_CLAW_P",
                    "name": "ATC Claw Tool Gripper Cylinder Pressure",
                    "value": 5.5,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 10,
                    "warnLimit": 4.8,
                    "alarmLimit": 4.0,
                    "normal": "5.0 - 7.0 bar",
                    "alarm": "< 4.0 bar",
                    "backendZone": "green",
                    "sparkline": [5.6, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_PNEUMATIC_MAIN_AIR_FLOW",
                    "name": "Main Air Supply Mass Flow Rate",
                    "value": 420,
                    "unit": "Nm³/h",
                    "direction": "high",
                    "min": 0,
                    "max": 800,
                    "warnLimit": 600,
                    "alarmLimit": 720,
                    "normal": "150 - 550 Nm³/h",
                    "alarm": "≥ 720 Nm³/h",
                    "backendZone": "green",
                    "sparkline": [380, 395, 410, 415, 420, 420, 418, 422, 419, 420],
                    "analysis": None
                }
            ]
        },
        {
            "groupId": "hydraulics-workholding",
            "groupName": "Hydraulics & Pallet Workholding System",
            "description": "Central hydraulic power pack, pallet unclamp cylinders, counter-balance circuit per Hydraulic Schematic HS-002-K617-2",
            "parameters": [
                {
                    "tag": "BAVIUS_HYD_MAIN_PRESSURE",
                    "name": "Main Hydraulic System Pressure",
                    "value": 135.0,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 200,
                    "warnLimit": 120.0,
                    "alarmLimit": 100.0,
                    "normal": "125 - 150 bar",
                    "alarm": "< 100 bar",
                    "backendZone": "green",
                    "sparkline": [136, 135, 135, 136, 135, 135, 135, 135, 135, 135],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_HYD_PALLET_CLAMP_P",
                    "name": "Hydraulic Clamping Line Pressure (Pallet Table)",
                    "value": 122.0,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 180,
                    "warnLimit": 110.0,
                    "alarmLimit": 90.0,
                    "normal": "115 - 140 bar",
                    "alarm": "< 90 bar",
                    "backendZone": "green",
                    "sparkline": [124, 123, 122, 122, 122, 122, 122, 122, 122, 122],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_HYD_RETURN_FILTER_DP",
                    "name": "Hydraulic Return Filter Differential Pressure",
                    "value": 2.1,
                    "unit": "bar",
                    "direction": "high",
                    "min": 0,
                    "max": 5.0,
                    "warnLimit": 1.8,
                    "alarmLimit": 2.5,
                    "normal": "0 - 1.8 bar",
                    "alarm": "≥ 2.5 bar",
                    "backendZone": "yellow",
                    "sparkline": [1.4, 1.5, 1.7, 1.8, 1.9, 2.0, 2.0, 2.1, 2.1, 2.1],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Return filter differential pressure reached 2.1 bar, indicating filter element particle loading.",
                        "probableReason": "Hydraulic oil micro-particulate varnish buildup in return circuit.",
                        "manualSolution": "1. Prepare 6-micron replacement filter cartridge.\n2. Relieve system hydraulic pressure via bleed valve 2V1.\n3. Replace filter element and check clogging indicator per Hydraulic Manual Ch. 4.",
                        "historicalCorrelation": "Correlates to Pallet Clamp Lockup failure mode (19 incidents in last 6 months).",
                        "sparesRequired": "Hydac Glass Fiber Filter Element 10 µm (P/N: 0160 D 010 BN4HC), Differential Pressure Optical/Electrical Clogging Indicator (P/N: VD 5 D.0 /-2M), Hydraulic Reservoir NBR Gasket Kit (P/N: NBR-RES-75)"
                    }
                },
                {
                    "tag": "BAVIUS_HYD_TANK_TEMP",
                    "name": "Hydraulic Reservoir Fluid Temperature",
                    "value": 41.5,
                    "unit": "°C",
                    "direction": "high",
                    "min": 10,
                    "max": 80,
                    "warnLimit": 52.0,
                    "alarmLimit": 62.0,
                    "normal": "30 - 50 °C",
                    "alarm": "≥ 62 °C",
                    "backendZone": "green",
                    "sparkline": [35.0, 36.5, 38.0, 39.5, 40.2, 40.8, 41.1, 41.3, 41.4, 41.5],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_HYD_ACCUM_N2_P",
                    "name": "Hydraulic Accumulator Nitrogen Pre-Charge",
                    "value": 68.0,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 120,
                    "warnLimit": 62.0,
                    "alarmLimit": 55.0,
                    "normal": "65 - 80 bar",
                    "alarm": "< 55 bar",
                    "backendZone": "green",
                    "sparkline": [70, 69, 69, 68, 68, 68, 68, 68, 68, 68],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_HYD_Z_COUNTERBALANCE_P",
                    "name": "Z-Axis Counterbalance Hydraulic Pressure",
                    "value": 88.0,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 140,
                    "warnLimit": 78.0,
                    "alarmLimit": 68.0,
                    "normal": "82 - 100 bar",
                    "alarm": "< 68 bar",
                    "backendZone": "green",
                    "sparkline": [89, 88, 88, 88, 88, 88, 88, 88, 88, 88],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_HYD_TANK_LEVEL_PERCENT",
                    "name": "Hydraulic Oil Tank Level",
                    "value": 78.0,
                    "unit": "%",
                    "direction": "low",
                    "min": 0,
                    "max": 100,
                    "warnLimit": 50.0,
                    "alarmLimit": 30.0,
                    "normal": "50 - 100 %",
                    "alarm": "< 30 %",
                    "backendZone": "green",
                    "sparkline": [80, 80, 79, 79, 79, 78, 78, 78, 78, 78],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_HYD_PALLET_UNCLAMP_TIME",
                    "name": "Pallet Unclamp Release Confirmation Time",
                    "value": 1.15,
                    "unit": "sec",
                    "direction": "high",
                    "min": 0,
                    "max": 4.0,
                    "warnLimit": 2.0,
                    "alarmLimit": 2.8,
                    "normal": "0.8 - 1.8 sec",
                    "alarm": "≥ 2.8 sec",
                    "backendZone": "green",
                    "sparkline": [1.10, 1.12, 1.14, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15, 1.15],
                    "analysis": None
                }
            ]
        },
        {
            "groupId": "motion-drives",
            "groupName": "5-Axis Motion Drives & Gantry Kinematics",
            "description": "Siemens S120 servo drives, tandem gantry drives (X11/X12), vertical column (Y11), and rotary axes per Drive Diagram Antriebsschema",
            "parameters": [
                {
                    "tag": "BAVIUS_DRV_Y11_MOTOR_TEMP",
                    "name": "Axis Y11 Motor Temp (Vertical Column)",
                    "value": 58.0,
                    "unit": "°C",
                    "direction": "high",
                    "min": 15,
                    "max": 90,
                    "warnLimit": 55.0,
                    "alarmLimit": 70.0,
                    "normal": "20 - 55 °C",
                    "alarm": "≥ 70 °C",
                    "backendZone": "yellow",
                    "sparkline": [38.0, 42.5, 47.0, 51.5, 54.0, 56.0, 57.0, 57.6, 57.8, 58.0],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Axis Y11 column drive motor temp reached 58.0 °C, crossing 55.0 °C warning boundary.",
                        "probableReason": "Hydraulic holding brake partial drag or slideway counter-balance pressure mismatch.",
                        "manualSolution": "1. Verify hydraulic brake release solenoid valve 1S1 operation.\n2. Inspect guideway lubrication oil metering valves for vertical ways.\n3. Check Z-column counterbalance accumulator pressure per HBZ CC Manual Ch. 3.4.",
                        "historicalCorrelation": "Led to drive torque trip 11 times in past 6 months (Top 5 breakdown cause).",
                        "sparesRequired": "Siemens 1FT7 Servomotor External Cooling Fan Blower (P/N: 1FT7-FAN-230V), Drive Motor Thermal Overload Sensor KTY84-130 (P/N: KTY84-130), THK Roller Guide Wiper Seal Kit (P/N: SRG45-WIP)"
                    }
                },
                {
                    "tag": "BAVIUS_DRV_Y11_CURRENT",
                    "name": "Axis Y11 Servo Current",
                    "value": 21.4,
                    "unit": "A",
                    "direction": "high",
                    "min": 0,
                    "max": 40,
                    "warnLimit": 18.0,
                    "alarmLimit": 28.0,
                    "normal": "0 - 18 A",
                    "alarm": "≥ 28 A",
                    "backendZone": "yellow",
                    "sparkline": [8.5, 11.2, 14.8, 17.5, 19.2, 20.4, 20.9, 21.2, 21.3, 21.4],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Elevated continuous servo current 21.4 A during rapid column traverse moves.",
                        "probableReason": "Mechanical resistance along vertical guideways or ballscrew pre-load drag.",
                        "manualSolution": "1. Inspect linear roller guideway shoes for lubrication starvation.\n2. Perform CNC automated brake test cycle.\n3. Verify ballscrew drive belt tension per Antriebsschema HBZ CC 200/100.",
                        "historicalCorrelation": "Precursor to Axis Drive Drag breakdown mode.",
                        "sparesRequired": "THK Precision Ball Screw Wiper Scraper (P/N: BSW-4010-RR), Klüberplex BEM 34-132 Synthetic Grease Cartridge (P/N: KLUB-34-132-400G), Flexible Cable Carrier Chain Link (P/N: IGUS 3500.100)"
                    }
                },
                {
                    "tag": "BAVIUS_DRV_Y11_TORQUE",
                    "name": "Axis Y11 Motor Torque (Brake Load)",
                    "value": 34.5,
                    "unit": "Nm",
                    "direction": "high",
                    "min": -60,
                    "max": 60,
                    "warnLimit": 28.0,
                    "alarmLimit": 42.0,
                    "normal": "-25 - +25 Nm",
                    "alarm": "≥ 42 Nm",
                    "backendZone": "yellow",
                    "sparkline": [12.0, 16.5, 22.0, 26.8, 30.2, 32.5, 33.6, 34.1, 34.4, 34.5],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Motor torque demand elevated at 34.5 Nm under nominal cutting conditions.",
                        "probableReason": "Vertical axis counter-balance pressure dip causing motor to carry extra gravity load.",
                        "manualSolution": "1. Measure counterbalance cylinder pressure (should be 88 bar).\n2. Top up nitrogen accumulator if pressure < 78 bar.\n3. Inspect guide rail wiper scrapers for aluminum chip ingress.",
                        "historicalCorrelation": "Corresponds to 11 previous drive overload events.",
                        "sparesRequired": "Vogel Central Lubrication Metering Valve Unit (P/N: 341-100-000), Linear Encoder Optical Scale Scanning Head (P/N: Heidenhain LC 195F), Gantry Crossbeam Linear Guide Bearing Block (P/N: THK SRG45LR)"
                    }
                },
                {
                    "tag": "BAVIUS_DRV_X11_FOLLOW_ERROR",
                    "name": "Axis X11 Master Gantry Position Lag",
                    "value": 0.008,
                    "unit": "mm",
                    "direction": "high",
                    "min": 0,
                    "max": 0.050,
                    "warnLimit": 0.025,
                    "alarmLimit": 0.038,
                    "normal": "0 - 0.020 mm",
                    "alarm": "≥ 0.038 mm",
                    "backendZone": "green",
                    "sparkline": [0.005, 0.006, 0.007, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008, 0.008],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_DRV_X12_SYNC_DEVIATION",
                    "name": "Axis X12 Slave Gantry Tandem Sync Deviation",
                    "value": 0.004,
                    "unit": "mm",
                    "direction": "high",
                    "min": 0,
                    "max": 0.030,
                    "warnLimit": 0.015,
                    "alarmLimit": 0.022,
                    "normal": "0 - 0.012 mm",
                    "alarm": "≥ 0.022 mm",
                    "backendZone": "green",
                    "sparkline": [0.003, 0.003, 0.004, 0.004, 0.004, 0.004, 0.004, 0.004, 0.004, 0.004],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_DRV_Z11_MOTOR_TEMP",
                    "name": "Axis Z11 Ram Extension Motor Temperature",
                    "value": 44.2,
                    "unit": "°C",
                    "direction": "high",
                    "min": 15,
                    "max": 90,
                    "warnLimit": 55.0,
                    "alarmLimit": 70.0,
                    "normal": "20 - 55 °C",
                    "alarm": "≥ 70 °C",
                    "backendZone": "green",
                    "sparkline": [32, 35, 38, 41, 43, 44, 44, 44, 44, 44.2],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_DRV_A11_CURRENT",
                    "name": "Axis A11 Swivel Trunnion Motor Current",
                    "value": 8.4,
                    "unit": "A",
                    "direction": "high",
                    "min": 0,
                    "max": 30,
                    "warnLimit": 15.0,
                    "alarmLimit": 22.0,
                    "normal": "0 - 15 A",
                    "alarm": "≥ 22 A",
                    "backendZone": "green",
                    "sparkline": [4.0, 5.5, 6.8, 7.8, 8.1, 8.3, 8.4, 8.4, 8.4, 8.4],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_DRV_C11_MOTOR_TEMP",
                    "name": "Axis C11 Direct-Drive Torque Motor Temperature",
                    "value": 38.6,
                    "unit": "°C",
                    "direction": "high",
                    "min": 15,
                    "max": 75,
                    "warnLimit": 48.0,
                    "alarmLimit": 58.0,
                    "normal": "20 - 45 °C",
                    "alarm": "≥ 58 °C",
                    "backendZone": "green",
                    "sparkline": [28, 30, 33, 35, 37, 38, 38.2, 38.4, 38.5, 38.6],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_SCALE_X11_SIGNAL_AMP",
                    "name": "Heidenhain Linear Scale X11 Signal Amplitude",
                    "value": 1.02,
                    "unit": "Vss",
                    "direction": "low",
                    "min": 0,
                    "max": 1.5,
                    "warnLimit": 0.85,
                    "alarmLimit": 0.65,
                    "normal": "0.90 - 1.20 Vss",
                    "alarm": "< 0.65 Vss",
                    "backendZone": "green",
                    "sparkline": [1.05, 1.04, 1.03, 1.03, 1.02, 1.02, 1.02, 1.02, 1.02, 1.02],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ENCODER_C11_SIGNAL_AMP",
                    "name": "Heidenhain Angle Encoder C11 Signal Amplitude",
                    "value": 0.98,
                    "unit": "Vss",
                    "direction": "low",
                    "min": 0,
                    "max": 1.5,
                    "warnLimit": 0.82,
                    "alarmLimit": 0.60,
                    "normal": "0.85 - 1.15 Vss",
                    "alarm": "< 0.60 Vss",
                    "backendZone": "green",
                    "sparkline": [1.00, 0.99, 0.99, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98, 0.98],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_LUBE_WAY_PRESSURE",
                    "name": "Slideway Progressive Way Lube Pressure",
                    "value": 28.5,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 50,
                    "warnLimit": 22.0,
                    "alarmLimit": 16.0,
                    "normal": "24 - 35 bar",
                    "alarm": "< 16 bar",
                    "backendZone": "green",
                    "sparkline": [29, 29, 28.5, 28.5, 28.5, 28.5, 28.5, 28.5, 28.5, 28.5],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_LUBE_CYCLE_TIME",
                    "name": "Progressive Distributor Lube Cycle Confirmation Time",
                    "value": 12.0,
                    "unit": "sec",
                    "direction": "high",
                    "min": 0,
                    "max": 30,
                    "warnLimit": 18.0,
                    "alarmLimit": 24.0,
                    "normal": "8 - 16 sec",
                    "alarm": "≥ 24 sec",
                    "backendZone": "green",
                    "sparkline": [11, 11, 12, 12, 12, 12, 12, 12, 12, 12],
                    "analysis": None
                }
            ]
        },
        {
            "groupId": "tool-changer",
            "groupName": "Automatic Tool Changer (ATC) & Gripper Magazine",
            "description": "Chain tool magazine, shutter doors, pneumatic transfer arm, and proximity sensors per Tool Control Manual 146598",
            "parameters": [
                {
                    "tag": "BAVIUS_ATC_CHAIN_MOTOR_CURR",
                    "name": "Tool Magazine Chain Drive Motor Current",
                    "value": 4.2,
                    "unit": "A",
                    "direction": "high",
                    "min": 0,
                    "max": 15,
                    "warnLimit": 8.0,
                    "alarmLimit": 11.0,
                    "normal": "2 - 7 A",
                    "alarm": "≥ 11 A",
                    "backendZone": "green",
                    "sparkline": [3.8, 4.0, 4.1, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2, 4.2],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ATC_DOOR_CYCLE_TIME",
                    "name": "ATC Shutter Door Pneumatic Cycle Time",
                    "value": 0.88,
                    "unit": "sec",
                    "direction": "high",
                    "min": 0,
                    "max": 3.0,
                    "warnLimit": 1.5,
                    "alarmLimit": 2.2,
                    "normal": "0.6 - 1.4 sec",
                    "alarm": "≥ 2.2 sec",
                    "backendZone": "green",
                    "sparkline": [0.85, 0.86, 0.87, 0.88, 0.88, 0.88, 0.88, 0.88, 0.88, 0.88],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ATC_SENSOR_B47_GAP",
                    "name": "Tool Clamp Confirmation Proximity Sensor B47 Signal",
                    "value": 1.8,
                    "unit": "mm",
                    "direction": "high",
                    "min": 0,
                    "max": 5.0,
                    "warnLimit": 3.0,
                    "alarmLimit": 3.8,
                    "normal": "1.2 - 2.6 mm",
                    "alarm": "≥ 3.8 mm",
                    "backendZone": "green",
                    "sparkline": [1.7, 1.7, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ATC_CHIP_TO_CHIP_TIME",
                    "name": "Tool Change Chip-to-Chip Duration",
                    "value": 7.2,
                    "unit": "sec",
                    "direction": "high",
                    "min": 0,
                    "max": 15.0,
                    "warnLimit": 9.5,
                    "alarmLimit": 12.0,
                    "normal": "5.5 - 8.5 sec",
                    "alarm": "≥ 12.0 sec",
                    "backendZone": "green",
                    "sparkline": [7.0, 7.1, 7.1, 7.2, 7.2, 7.2, 7.2, 7.2, 7.2, 7.2],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ATC_TOOL_LIFE_CYCLES",
                    "name": "Total Tool Indexing Operations Count",
                    "value": 382,
                    "unit": "cycles",
                    "direction": "high",
                    "min": 0,
                    "max": 1000,
                    "warnLimit": 750,
                    "alarmLimit": 900,
                    "normal": "0 - 750 cycles",
                    "alarm": "≥ 900 cycles",
                    "backendZone": "green",
                    "sparkline": [350, 355, 362, 368, 372, 376, 379, 380, 381, 382],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ATC_POCKET_LOCK_GAP",
                    "name": "Tool Pocket Mechanical Seat Lock Sensor Gap",
                    "value": 0.95,
                    "unit": "mm",
                    "direction": "high",
                    "min": 0,
                    "max": 3.0,
                    "warnLimit": 1.8,
                    "alarmLimit": 2.4,
                    "normal": "0.5 - 1.5 mm",
                    "alarm": "≥ 2.4 mm",
                    "backendZone": "green",
                    "sparkline": [0.92, 0.93, 0.94, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95, 0.95],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ATC_TAPER_PURGE_OK",
                    "name": "Tool Taper Air Blast Purge Cleanliness Ratio",
                    "value": 99.4,
                    "unit": "%",
                    "direction": "low",
                    "min": 0,
                    "max": 100,
                    "warnLimit": 85.0,
                    "alarmLimit": 70.0,
                    "normal": "90 - 100 %",
                    "alarm": "< 70 %",
                    "backendZone": "green",
                    "sparkline": [100, 100, 100, 99.8, 99.6, 99.5, 99.4, 99.4, 99.4, 99.4],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_ATC_SPRING_CYCLES",
                    "name": "Tool Holder Clamping Belleville Spring Cycle Count",
                    "value": 18450,
                    "unit": "act",
                    "direction": "high",
                    "min": 0,
                    "max": 50000,
                    "warnLimit": 35000,
                    "alarmLimit": 45000,
                    "normal": "0 - 35,000 act",
                    "alarm": "≥ 45,000 act",
                    "backendZone": "green",
                    "sparkline": [18200, 18250, 18300, 18350, 18380, 18400, 18420, 18440, 18445, 18450],
                    "analysis": None
                }
            ]
        },
        {
            "groupId": "aux-systems",
            "groupName": "Filtration, Vacuum Clamping & Auxiliary Subsystems",
            "description": "Knoll KF 200 filter fleece, VOC vacuum part clamping station, mist collector per Knoll KF & VOC Manuals",
            "parameters": [
                {
                    "tag": "BAVIUS_VACUUM_CLAMP_PRESSURE",
                    "name": "Vacuum Workholding Clamping Pressure",
                    "value": -560,
                    "unit": "mbar",
                    "direction": "high",
                    "min": -1000,
                    "max": 0,
                    "warnLimit": -600,
                    "alarmLimit": -500,
                    "normal": "-800 - -600 mbar",
                    "alarm": "≥ -500 mbar (Loss of Clamp)",
                    "backendZone": "yellow",
                    "sparkline": [-740, -710, -680, -650, -620, -595, -580, -570, -565, -560],
                    "analysis": {
                        "severity": "Medium",
                        "riskyTrend": "Vacuum hold-down degraded to -560 mbar, crossing warning threshold -600 mbar.",
                        "probableReason": "Workpiece sealing foam gasket micro-tears or fluid ingress into vacuum suction cup channels.",
                        "manualSolution": "1. Inspect vacuum foam rubber sealing perimeter for cuts or swarf chips.\n2. Open manual drain cock on liquid separator vessel 2V2.\n3. Verify vacuum pump suction filter differential per VOC Manual Ch. 3.",
                        "historicalCorrelation": "Led to aerostructure workpiece clamping warning 3 times in last 6 months.",
                        "sparesRequired": "VOC-AD-S Vacuum Suction EPDM Rubber Seal Lip 8mm (P/N: VOC-SEAL-8M), Busch Vacuum Pump Exhaust Filter Separator (P/N: 0532 140 157), Vacuum Non-Return Check Valve 1-inch (P/N: VCV-100-NBR)"
                    }
                },
                {
                    "tag": "BAVIUS_COOLANT_HP_DELIVERY_P",
                    "name": "Knoll KF 200 Coolant High-Pressure Delivery",
                    "value": 68.5,
                    "unit": "bar",
                    "direction": "low",
                    "min": 0,
                    "max": 100,
                    "warnLimit": 55.0,
                    "alarmLimit": 40.0,
                    "normal": "60 - 80 bar",
                    "alarm": "< 40 bar",
                    "backendZone": "green",
                    "sparkline": [70, 69.5, 69, 68.8, 68.6, 68.5, 68.5, 68.5, 68.5, 68.5],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_COOLANT_TANK_TEMP",
                    "name": "Knoll Clean Tank Emulsion Temperature",
                    "value": 23.4,
                    "unit": "°C",
                    "direction": "high",
                    "min": 10,
                    "max": 45,
                    "warnLimit": 30.0,
                    "alarmLimit": 36.0,
                    "normal": "18 - 28 °C",
                    "alarm": "≥ 36 °C",
                    "backendZone": "green",
                    "sparkline": [21.5, 21.8, 22.2, 22.6, 22.9, 23.1, 23.2, 23.3, 23.4, 23.4],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_FILTER_FLEECE_ADV_RATE",
                    "name": "Knoll Filter Fleece Advance Frequency",
                    "value": 2.8,
                    "unit": "m/h",
                    "direction": "high",
                    "min": 0,
                    "max": 8.0,
                    "warnLimit": 5.0,
                    "alarmLimit": 6.5,
                    "normal": "1.0 - 4.5 m/h",
                    "alarm": "≥ 6.5 m/h",
                    "backendZone": "green",
                    "sparkline": [2.5, 2.6, 2.6, 2.7, 2.7, 2.8, 2.8, 2.8, 2.8, 2.8],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_AFS_MIST_FILTER_DP",
                    "name": "AFS Oil Mist Collector Differential Pressure",
                    "value": 420,
                    "unit": "Pa",
                    "direction": "high",
                    "min": 0,
                    "max": 1200,
                    "warnLimit": 750,
                    "alarmLimit": 950,
                    "normal": "200 - 650 Pa",
                    "alarm": "≥ 950 Pa",
                    "backendZone": "green",
                    "sparkline": [380, 390, 400, 405, 410, 415, 418, 420, 420, 420],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CNC_FEED_OVERRIDE",
                    "name": "CNC Feedrate Override Knob Setting",
                    "value": 100.0,
                    "unit": "%",
                    "direction": "high",
                    "min": 0,
                    "max": 120,
                    "warnLimit": 110.0,
                    "alarmLimit": 115.0,
                    "normal": "80 - 100 %",
                    "alarm": "> 115 %",
                    "backendZone": "green",
                    "sparkline": [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_CNC_RAPID_OVERRIDE",
                    "name": "Rapid Traverse Override Knob Setting",
                    "value": 100.0,
                    "unit": "%",
                    "direction": "high",
                    "min": 0,
                    "max": 100,
                    "warnLimit": 100.0,
                    "alarmLimit": 100.0,
                    "normal": "50 - 100 %",
                    "alarm": "N/A",
                    "backendZone": "green",
                    "sparkline": [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
                    "analysis": None
                },
                {
                    "tag": "BAVIUS_PROBE_BATTERY_PERCENT",
                    "name": "Renishaw RMI-Q Radio Probe Battery Level",
                    "value": 92.0,
                    "unit": "%",
                    "direction": "low",
                    "min": 0,
                    "max": 100,
                    "warnLimit": 30.0,
                    "alarmLimit": 15.0,
                    "normal": "30 - 100 %",
                    "alarm": "< 15 %",
                    "backendZone": "green",
                    "sparkline": [95, 95, 94, 94, 93, 93, 93, 92, 92, 92],
                    "analysis": None
                }
            ]
        }
    ]
    return groups

if __name__ == '__main__':
    groups = get_bavius_parameters()
    all_params = [p for g in groups for p in g['parameters']]
    greens = [p for p in all_params if p['backendZone'] == 'green']
    yellows = [p for p in all_params if p['backendZone'] == 'yellow']
    reds = [p for p in all_params if p['backendZone'] == 'red']
    print(f"Total: {len(all_params)} | Green: {len(greens)} | Yellow: {len(yellows)} | Red: {len(reds)}")
